name: "text"
backend: "npu_ge"

input [
  {
    name: "text"
    data_type: TYPE_FP32
    dims: [1, 512  ]
  }
]
max_batch_size: 0
output [
  {
    name: "unnorm_text_features"
    data_type: TYPE_FP32
    dims: [1,512 ]
  }
]

instance_group [{ 
  kind: KIND_CPU
  count: 4
}
]



parameters: [
{
  key: "DEVICEIDS",
  value: {string_value: "4"}
}
]

