name: "image"
backend: "npu_ge"

input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [3, 224, 224 ]
  }
]
max_batch_size: 8
output [
  {
    name: "unnorm_image_features"
    data_type: TYPE_FP32
    dims: [512 ]
  }
]

instance_group [{
  count: 4
}
]

parameters: [
{
  key: "device_ids",
  value: {string_value: "4,5,6"}
}
]

